# Generated by Django 3.2.4 on 2021-06-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo_parroquia', models.CharField(choices=[('rural', 'Parroquia rural'), ('urbana', 'Parroquia urbana')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Parroquias',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('viviendas', models.IntegerField(verbose_name='numero de viviendas')),
                ('parques', models.IntegerField(choices=[(1, 'Un Parque'), (2, 'Dos Parques'), (3, 'Dos Parques'), (4, 'Dos Parques'), (5, 'Dos Parques'), (6, 'Dos Parques')], verbose_name='numero de parques')),
                ('edificios', models.IntegerField(verbose_name='numero de edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
